### ISSUE TITLE
Upgrade to Python 3.x?

### ISSUE THREAD

**Issue by ReedJessen** [JeroenKools/tradeviz#9]
Hello @Junuxx ,  

I think this is a really cool project but seems to not be very active.  I would like use some of the code in my current project.  In doing this, I am updating it to python 3.x. 

Would you accept a pull request of this 3.x upgrade or would you rather I fork it and have a python 3.x version available as well?

**Comment by JeroenKools** [comment]
Sorry I missed this issue entirely! 

FWIW the project moved to Python 3 as of 94a607b89a3f33854916069a4a7e24d40ebc5172
